name: Test Selenium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Installation de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installation des dépendances
      run: |
        pip install -r requirements.txt

    - name: Lancer le test Selenium
      run: |
        python testnavigation.py
